name: Dream Holiday
favicon: null
layout_spectrum: 0.7678580917418003
typography_spectrum: 0.0909381303936243
title: Ideen für den traumhaften Urlaub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4595e7'
    - '#00507c'
    - '#e4d8ca'
    - '#5e6200'
    - '#caa800'
  brandStrength: 0.6875
  lightness: 0.8689545595552772
  saturation: 0.625
  rhythmicContrast: 0.46924568293616176
purpose: []
