name: Traumurlaub
favicon: null
layout_spectrum: 0.49289
typography_spectrum: 0.48505
title: Ideen für den traumhaften Urlaub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#015da8'
    - '#ffffff'
    - '#d1c4b4'
    - '#5879b0'
    - '#93520e'
  brandStrength: 0.5
  lightness: 0.8689545595552772
  saturation: 0.5
  rhythmicContrast: 0.46924568293616176
purpose: []
